name: Build (Gradle)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:

  build:

    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        if: matrix.os == 'ubuntu-latest'
        with:
            dotnet-version: '3.1.x'

      - name: Setup MSBuildSDKsPath
        if: matrix.os == 'ubuntu-latest'
        run: echo "MSBuildSDKsPath=/usr/share/dotnet/sdk/$(dotnet --version)/Sdks/" >> $GITHUB_ENV

      - name: Build
        run: ./gradlew -is --console plain nunit repack nugetPack

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: NuGet Packages
          path: build\distributions
